name: Python publish to pypi

on:
  push:
    branches:
      - 'main'
      - '!develop'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Gr1N/setup-poetry@v8
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --all-extras
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}
          poetry publish --build