name: Python Unit Tests

on: [push]

jobs:
  unittest:
    env:
      MONGO_CONNECTION_STR = 'mongodb+srv://${{secrets.MONGO_USER}}:${{secrets.MONGO_PASSWORD}}@${{secrets.MONGO_URL}}'
      MONGO_DATABASE_NAME = 'traducteur'
      SQL_CONNECTION_STR = 'sqlite:///test.db'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: Gr1N/setup-poetry@v8
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry export -f requirements.txt --output requirements.txt -E mongo -E tasks
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest