name: Python Unit Tests

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        redis-version: [4, 5, 6]

    steps:
      - uses: actions/checkout@v3
      - uses: Gr1N/setup-poetry@v8
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup local redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry export -f requirements.txt --output requirements.txt -E all
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          export MONGO_CONNECTION_STR="mongodb+srv://${{secrets.MONGO_USER}}:${{secrets.MONGO_PASSWORD}}@${{secrets.MONGO_URL}}"
          export SQL_CONNECTION_STR="sqlite:///./test.db"
          export MONGO_DATABASE_NAME="traducteur"
          python -m unittest
